name: python37-nmctseb
version: 3.7.0
summary: Python language interpreter and standard library
description: |
  Python is a programming language that lets you work quickly and
  integrate systems more effectively.

grade: devel
confinement: strict

slots:
  python3:
    interface: content
    content: python3
    read:
      - $SNAP
  python37:
    interface: content
    content: python37
    read:
      - $SNAP

apps:
  python3:
    command: bin/python3
    aliases:
      - python3
      - python3.7
  pydoc3:
    command: bin/python3 -m pydoc
    aliases:
      - pydoc3
      - pydoc3.7
  pip3:
    command: bin/python3 -m pip
    aliases:
      - pip3
      - pip3.7

parts:
  compiler-wrapper:
    plugin: nil
    source: tools
    install: |
      sed -e "s/@CC@/${CC:-gcc}/g" \
          -e "s/@TRIPLET@/$(dpkg-architecture -q DEB_TARGET_MULTIARCH)/g" \
          compiler.sh.in > $SNAPCRAFT_PART_INSTALL/compiler.sh
      chmod a+x $SNAPCRAFT_PART_INSTALL/compiler.sh
    prime:
      - -*
    build-packages:
      - gcc
      - dpkg-dev

  python:
    after:
      - compiler-wrapper
    plugin: autotools
    source: https://www.python.org/ftp/python/3.7.0/Python-3.7.0.tar.xz
    configflags:
      - --enable-shared
      - --enable-ipv6
      - --enable-loadable-sqlite-extensions
      - --with-dbmliborder=bdb:gdbm
      - --with-computed-gotos
      - --with-ensurepip=upgrade
      - --with-system-expat
      - --with-system-libmpdec
      - --with-system-ffi
      - --with-fpectl
    install-via: prefix
    make-parameters:
      - CC=$SNAPCRAFT_STAGE/compiler.sh

    filesets:
      python:
        - bin/
        - lib/
        - -bin/*-config
        - -lib/python3.7/test/
        - -lib/python3.7/*/test/
        - -lib/python3.7/*/tests/
        - -lib/python3.7/idle/idle_test/
        - -lib/python3.7/lib-dynload/_*test*.so
        - -lib/pkgconfig
      tests:
        - lib/python3.7/test/
        - lib/python3.7/*/test/
        - lib/python3.7/*/tests/
        - lib/python3.7/idle/idle_test/
        - lib/python3.7/lib-dynload/_*test*.so
      manpages:
        - share/man/
      dev:
        - bin/*-config
        - include/
        - lib/pkgconfig/

    prime:
      - $python
      - $manpages
      - $dev

    build-packages:
      - gcc
      - libreadline-dev
      - libncursesw5-dev
      - zlib1g-dev
      - libbz2-dev
      - liblzma-dev
      - libgdbm-dev
      - libdb-dev
      - libssl-dev
      - libexpat1-dev
      - libmpdec-dev
      - libbluetooth-dev
      - libsqlite3-dev
      - libffi-dev

  sitecustomize:
    after:
      - python
    plugin: dump
    source: src
    organize:
      '*': lib/python3.7/site-packages/

    install: |
      set -x
      # byte compile sitecustomize.py
      installdir=$SNAPCRAFT_PART_INSTALL
      primedir=lib/python3.7/site-packages
      $SNAPCRAFT_STAGE/bin/python3.7 -Wi -m compileall -d $primedir $installdir
      $SNAPCRAFT_STAGE/bin/python3.7 -O -Wi -m compileall -d $primedir $installdir
      $SNAPCRAFT_STAGE/bin/python3.7 -OO -Wi -m compileall -d $primedir $installdir

